USACE/cumulus-ui

- src/app-pages/profile/my-tokens.js
- src/app-pages/profile/profile.js
> fix UI styles on profile

- src/app-bundles/download-bundle.js
- src/app-bundles/index.js
- src/app-pages/dashboard/downloads/downloads.js
> progress update polling

- src/app-bundles/index.js
> new api url

- src/app-pages/catalog/product-details.js
> adjust heatmap color range

- package-lock.json
- package.json
- src/App.js
- src/app-components/navbar.js
- src/app-components/page-heading.js
- src/app-components/sub-navbar.js
- src/app-pages/catalog/catalog.js
- src/app-pages/catalog/product-details.js
> Catalog Redesign

- src/app-components/actions/Datepicker.js
- src/app-pages/contact/index.js
- src/app-pages/docs/index.js
- src/app-pages/docs/rts-script.js
- src/app-pages/help/index.js
- src/app-pages/home/latest-updates.js
This should fix https://github.com/USACE/cumulus/issues/155
> fix class= to className= and misc cleanup

- src/app-bundles/download-bundle.js
resolves https://github.com/USACE/cumulus/issues/162
> enable prefetch, forceFetchAction for login

- package-lock.json
- package.json
- src/app-bundles/download-metrics-bundle.js
* change download metrics bundle endpoint
* 1.0.1
> Fix/download metrics endpoint (#72)

- package-lock.json
- package.json
- src/app-bundles/route-bundle.js
- src/app-components/admin/AdminWrapper.js
- src/app-components/admin/Sidebar.js
- src/app-pages/admin/accounts.js
- src/app-pages/admin/accounts/index.js
- src/app-pages/admin/downloads/download-stats.js
- src/app-pages/admin/downloads/index.js
- src/app-pages/admin/parameters/index.js
- src/app-pages/admin/products.js
- src/app-pages/admin/products/index.js
- src/app-pages/admin/suites/index.js
- src/app-pages/admin/tags/index.js
- src/app-pages/admin/units/index.js
- src/app-pages/admin/watersheds.js
- src/app-pages/admin/watersheds/index.js
- src/app-pages/home/index.js
* cleanup code with new AdminWrapper, add new admin download page
* 1.0.2
> Feature/admin wrapper cleanup (#78)

- src/app-bundles/index.js
> Include JWT on GET /my_downloads; Delete unused config parameter root

- package-lock.json
- package.json
- src/app-pages/products/product-details/product-properties.js
closes https://github.com/USACE/cumulus/issues/158
> latest forecast metadata field added

- src/app-pages/products/download-modal.js
fixes https://github.com/USACE/cumulus/issues/195
> removed setting hours and minutes to zero

- src/app-bundles/product-filter-bundle.js
- src/app-pages/products/products.js
Quick little logic fix so that filtering for tags contributes to an AND style query.
> Fix filtering

- package-lock.json
- src/app-bundles/download-bundle.js
Fixes USACE/cumulus#212. Updates several JavaScript dependencies.
> Fixes In-Progress Download Polling; Bot JS Dependency Updates

- package-lock.json
- package.json
- src/app-pages/products/download-modal.js
* restrict to 6 months
* 1.3.3
> Feature/restrict download time window (#124)

- src/app-pages/products/download-modal.js
- src/app-pages/products/product-details/index.js
* add download buttons to product details page
* allow products to be removed from download modal
> Feature/product page download buttons (#131)

- .github/workflows/develop.yml
- .github/workflows/stable.yml
- package-lock.json
- package.json
- src/app-pages/products/download-modal.js
* date limit restrictions added
* 1.3.9
https://github.com/USACE/cumulus/issues/331
> Feature/331 adjust download modal date selections (#155)

- package-lock.json
- package.json
- src/app-bundles/index.js
- src/app-bundles/project-ingest-status.js
- src/app-pages/products/product-details/product-properties.js
- src/app-pages/products/products-table/products-table-row.js
Develop changes to indicate potentially late products merging into stable.
> Changes in develop going to stable

- package-lock.json
- package.json
- src/app-bundles/dss-datatype-bundle.js
- src/app-bundles/index.js
- src/app-bundles/suite-bundle.js
- src/app-bundles/unit-bundle.js
- src/app-components/admin/modals/edit-product-modal.js
- src/app-pages/products/product-details/product-properties.js
* add new dssDatatype bundle
* trigger fetch based on product saved action
* add dss datatype dropdown field
* add dss datatype to product details
* 1.4.1
> Bugfix/330 dss datatype id fix (#160)

- package-lock.json
- package.json
* upgrade packages
* 1.4.2
https://github.com/USACE/cumulus/issues/369
> upgrade packages (#162)

- src/app-bundles/download-bundle.js
https://github.com/USACE/cumulus/issues/370
> only evaluate downloads in the last 8 hours

- src/app-bundles/download-bundle.js
https://github.com/USACE/cumulus/issues/371
> resolve silly finding.
